apiVersion: 1

datasources:
  - name: InfluxDB
    uid: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: iot_data
    secureJsonData:
      token: admin123